FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=development

RUN npx prisma generate

EXPOSE 8103

CMD ["npm", "run", "dev"]
